### ISSUE TITLE
EventBus Subscribers not working with notify method

### ISSUE THREAD

**Issue by gubler** [SimpleBus/SimpleBus#59]
When I use the EventBus in a Symfony 4 app with autowiring, I have to use `__invoke()` for the method to be called in the subscriber. However, the docs state that I _should_ be able to use either `__invoke` or `notify`.

Is this wrong in the documentation, or is there some configuration I'm missing.

My service declaration:
```yaml
    App\Domain\Subscriber\:
        resource: '../src/Domain/Subscriber'
        tags: [event_subscriber]
        public: true
```

And my event subscriber (this is edited for brevity):
```php
<?php

namespace App\Domain\Subscriber\Project\Issue;

use App\Domain\Event\Project\Issue\IssueCreatedEvent;

class IssueCreatedEventSubscriber
{
    public function __notify(IssueCreatedEvent $event): void
    {
        // ... code that does stuff when event is received
    }
}
```

This works, but if I change ```public function __invoke(IssueCreatedEvent $event): void``` to ```public function notify(IssueCreatedEvent $event): void```, the event subscriber is no longer called.

Digging in a little deeper, it looks to be something with how the EventBusBridge compiler pass is looking for Event Subscribers. When I run ```bin/console debug:container IssueCreatedEventSubscriber```, I can see the ```event_subscriber``` tag, but if I change the method to ```notify```, the tag is no longer applied to the service.

I'm not sure what the difference is between the EventBusBridge compiler pass and the CommandBusBridge compiler pass. My command handlers work with both ```__invoke``` and ```handle```.

When I look in ```SimpleBusEventBusBundle.php```, I see the following:

```php
$container->addCompilerPass(
    new RegisterSubscribers(
        'simple_bus.event_bus.event_subscribers_collection',
        'event_subscriber',
        'subscribes_to'
    )
);
```

I tried changing ```__invoke``` to either ```subscribes_to``` or ```subscribesTo```, but neither worked.

So, is this a bug, an error in documentation (and I have to use __invoke), or am I messing something up?

And if it is an error in documentation, why can we use ```handle``` in command handlers, but not ```notify``` in event subscribers?

**Comment by samijnih** [comment]
Hey :)

`register_public_methods: true` does not work for me.

Looking at https://github.com/SimpleBus/SymfonyBridge/blob/6c6b24ebfbf6341c1fa7c5aa23b0c757ba472e7c/src/SimpleBusEventBusBundle.php#L55

I can't figure out where the code loads services with `key_attribute = 'register_public_methods'`.

My yaml file:

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Application\PublicContext\UseCases\User\Write\ConfirmUserEmail\CreateUserProfileOnUserEmailConfirmed:
        tags:
            - { name: event_subscriber, subscribes_to: user_email_confirmed }

    Infrastructure\Listener\OnPersistence\Book\UpdateReadModelOnRegisteredBook:
        tags:
            - { name: event_subscriber, register_public_methods: true }
```

When I  dump in AutoRegister::process doing:

![image](https://user-images.githubusercontent.com/10528754/99302485-bc343e80-284f-11eb-809c-0c5d5d84e656.png)

It shows me:

![image](https://user-images.githubusercontent.com/10528754/99302524-c8b89700-284f-11eb-83ed-436964b10a2b.png)

It is an issue or I am doing something wrong? We can see my first domain event listener is properly registered but not my second on `UpdateReadModelOnRegisteredBook`

Thanks :)
